export const wigs = [
    {
        id: 'frizz123',
        name: 'The Ms. Frizzle',
        image: 'the-ms-frizzle.jpg',
        imageAlt: 'The Ms. Frizzle Wig',
        description: 'A look that screams "kooky grade school teacher takes students on a field trip," but cute.',
        category: 'going out',
        price: 44.99,
    },
    {
        id: 'bob123',
        name: 'The Asymmetrical Number',
        image: 'the-asymmetrical-number.png',
        // imageAlt: 'The Ms. Frizzle Wig',
        description: 'A stunning little number that can\'t decide what length it wants to be.',
        category: 'staying in',
        price: 39.99,
    },
    {
        id: 'cyn123',
        name: 'The Cyndi Lauper',
        image: 'the-cyndi-lauper.jpg',
        description: 'This wig looks like it has been round-brushed within an inch of its life — in a good way. The blonde streaks frame her face before flipping skyward. It\'s a vibe we hope she keeps coming back to "time after time" (get it?).',
        category: 'staying in',
        price: 46.99,
    },
    {
        id: 'lob123',
        name: 'The Luau Lob',
        image: 'the-luau-lob.jpg',
        description: 'We learn that this wig\'s name is Maureen, and "she doesn\'t like to be manhandled." She certainly has a lot of personality, as is evidenced by the blonde layered over slightly longer black. It\'s a weird look, and no one but Moira could pull it off so effortlessly.',
        category: 'going out',
        price: 57.99,
    },
    {
        id: 'queen123',
        name: 'The Queen Elizabeth I, But Make It Punk',
        image: 'the-queen-elizabeth-i-but-make-it-punk.jpg',
        description: 'Paired with her Tudor ruff and pearl drop earrings, Moira looks like she just Outlander-ed herself forward in time and learned about hairspray somewhere along the way. It\'s a magnificent disaster.',
        category: 'going out',
        price: 42.75,
    },
    {
        id: 'ex123',
        name: 'The Existential Crisis Bob',
        image: 'existential-crisis-bob.jpg',
        description: 'Moira dons this gray number after being frustrated about what people are saying about her online. It frames her face well, but it\'s a bit too ordinary for the great Moira Rose to wear on a daily basis.',
        category: 'staying in',
        price: 20.21,
    },
];